services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taskmaster-fe-dev
    environment:
      - INTERNAL_API_BASE=${INTERNAL_API_BASE}
    env_file:
      - ./.env
    restart: always
