services:
  db:
    image: postgres:15
    container_name: taskmaster_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: taskmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taskmaster_api_dev
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/taskmaster
      - FLASK_DEBUG=1
      - JWT_SECRET_KEY=dev_secret_key
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data_dev:
